### ISSUE TITLE
Runner is not able to use mysql sockets

### ISSUE THREAD

**Issue by mitaka** [humanmade/Cavalcade-Runner#14]
When we configure wordpress to connec to the database with mysql socket the runner fails to start. We can reproduce it by adding this line to wp-config.php:

define( 'DB_HOST', 'localhost:/tmp/mysql.sock' );

**Comment by rmccue** [comment]
As it turns out, WordPress [shims this in for mysqli](https://github.com/WordPress/WordPress/blob/2a76ccac4e07dcc7bac802a3f2e0862221dbe2c1/wp-includes/wp-db.php#L1498-L1516), so we should be able to use the same approach.
