### ISSUE TITLE
log location when using xenial xerus

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/Cavalcade-Runner#31]
So looking at a way to direct Cc logs to their own files in 16.04, since Systemd seems to have its own ideas.

I would have liked to handle this in salt but not sure how. The most direct approach to change https://github.com/humanmade/Cavalcade-Runner/blob/master/systemd.service#L11 

To something like `ExecStart=/bin/bash -c 'exec /etc/cavalcade/bin/cavalcade &>> /var/log/cavalcade.log '`.

cc @joehoyle

**Comment by rmccue** [comment]
It seems like the best way to do this would be using journald, rather than changing the service script.

What's the use case for having the logs in plain text files? Do we need that to feed to CloudWatch?

**Comment by owaincuvelier** [comment]
>It seems like the best way to do this would be using journald, rather than changing the service script.

I know, I didn't like doing it in such a messy way. But as I understand it lots of systemd services write to the journal correct?

>What's the use case for having the logs in plain text files? Do we need that to feed to CloudWatch?

That's my assumption yes.

**Comment by rmccue** [comment]
All units (services) write to the journal, which is basically a binary log. You can get it back out pretty easily though, since it's all stored per unit.

**Comment by rmccue** [comment]
Looks like we should be able to use https://github.com/saymedia/journald-cloudwatch-logs

**Comment by owaincuvelier** [comment]
if that's written in GO, we'll need the compiler on our webservers? Nice find though. Any thoughts @joehoyle?

**Comment by rmccue** [comment]
We could either build it ourselves once and put it on S3, or use the [prebuilt release binary](https://github.com/saymedia/journald-cloudwatch-logs/releases).

**Comment by owaincuvelier** [comment]
In the ended up setting `SyslogIdentifier=cavalcade` and write a conf in `rsyslog.d` to pipe to a separate log file, which the awslog agent can read from!
