### ISSUE TITLE
Lock a job when starting it

### ISSUE THREAD

**Issue by joehoyle** [humanmade/Cavalcade-Runner#41]
Right now we are seeing jobs being run more than once simultaneously because a job's "lock" is not quite atomic. We should probably use a `SELECT... FOR UPDATE` in https://github.com/humanmade/Cavalcade-Runner/blob/master/inc/class-runner.php#L221

**Comment by rmccue** [comment]
This should [already be handled](https://github.com/humanmade/Cavalcade-Runner/blob/52fa840f3fa45d4302b0de82cf6197c235980c9e/inc/class-runner.php#L248-L252)?

**Comment by joehoyle** [comment]
Yeah, not sure how I didn't see that
