### ISSUE TITLE
Add Cavalcade Runner to Homebrew

### ISSUE THREAD

**Issue by JPry** [humanmade/Cavalcade-Runner#50]
Related to #49, it would be nice to be able to install the Cavalcade Runner on a Mac using [Homebrew](https://brew.sh). Ideally that would enable `brew install cavalcade`, and put the executable from `bin/cavalcade` into the Homebrew directory. By default, this is `/usr/local/bin/`.

Homebrew includes documentation to [create and maintain a tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap). It's likely this would be the necessary approach, as the use of Cavalcade, especially on Mac OS, is probably too obscure to [qualify as a formula](https://docs.brew.sh/Acceptable-Formulae).

**Comment by rmccue** [comment]
As this isn't something we'd use at HM, we probably won't do this, as it'll be likely to fall out of date. If you want to set up and maintain one though, happy to add it to the readme as an unofficial source :)
