### ISSUE TITLE
SSL support for secure database connections

### ISSUE THREAD

**Issue by billybigpotatoes** [humanmade/Cavalcade-Runner#61]
Where hosts do/can not support Cavalcade-Runner of in the case where you want to use dedicated resources for processing cron - then the runner may need to subscribe to an external DB e.g. Amazon RDS.  

Best practice for external DB connections is to leverage SSL to protect data in transit.

It is possible to add support for DB requests via SSL to the runner.

This is not in WP core today - but there are plugins to provide this e.g. (from stackoverflow)

For those looking for a way to do this w/o hacking core or rolling your own plugin:

https://wordpress.org/plugins/secure-db-connection/

Created by the dev who initially reported the issue in WordPress: https://core.trac.wordpress.org/ticket/28625

**Comment by rmccue** [comment]
You should be able to do this already with the hooks in the runner:

https://github.com/humanmade/Cavalcade-Runner/blob/445a67194e295ab5d2fad0eaa7fb938c54f6d496/inc/class-runner.php#L192-L211

I'd say we should probably add this if/when WP does, or if we decide to support it officially across our platform, but currently I don't believe we are planning on this.
