### ISSUE TITLE
Install directory

### ISSUE THREAD

**Issue by henrywright** [humanmade/Cavalcade-Runner#67]
Hey

Where do you recommend I install the runner? I'm using Debian

**Comment by roborourke** [comment]
Hey @henrywright 

We use `/etc/cavalcade` and add the following symlink `ln -s /etc/cavalcade/bin/cavalcade /usr/local/bin/cavalcade`.

I'm not sure how familiar you are with puppet but this is how we set it up and configure it for our local development Ubuntu VMs https://github.com/Chassis/Cavalcade/blob/main/modules/cavalcade/manifests/init.pp

**Comment by henrywright** [comment]
Hey @roborourke 

I don't use Puppet actually. Would `nohup` do the job?

Is the symlink necessary because you have that directory in your path?

**Comment by roborourke** [comment]
The location ultimately doesn’t matter that much, we use /etc because that’s where other services live. The symlink just means the executable file is in the path.

I linked to the puppet manifest as it’s just a means of creating the config files and creating a service to ensure it’s running.

**Comment by henrywright** [comment]
I guess having the executable in my path will save me having to pass the path to my WordPress root folder to Cavalcade

Thanks for explaining. That has really helped

**Comment by roborourke** [comment]
No worries, I'll close this out for now but happy to continue the conversation 😄
